server:
  port: 8080

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TWEET-API
          uri: lb://TWEET-API
          predicates:
            - Path=/tweet/**
        - id: USER-API
          uri: lb://USER-API
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true
#    hostname: localhost



